From ubuntu
Maintainer Akash_Wadbude
Run apt-get update -y
#Copy /var/lib/jenkins/workspace/Job1/Project-123/SG-A/Project_X/Project_X /home/ubuntu/
# above command is copying Project_Z folder into container

